### PR TITLE
Update lgbtq_plus.md

### PR DESCRIPTION
**Pull request by norahqueen**
Added a section for Australia. Added the resources Switchboard Victoria, Queerspace, Q+Law, QLife and Rainbow Door to the section for Australia.

### CODE REVIEW

**Comment by norahqueen** [comment]
Going to leave this as a draft overnight (It's 7:30pm down under right now) to see if anything else comes to mind before submitting for review.

**Review by norahqueen — COMMENTED** [review]
I think this is a good start for now.

**Comment by norahqueen** [comment]
Heya, I had to bug you but I’m just wondering if there’s a reason this hasn’t been merged yet? I think it’s pretty important information to have up as soon as possible to support Australian members of LGBTQ+ and Beehaw as a whole.

**Comment by lionirdeadman** [comment]
I missed this, sorry! Thank you for the contribution.

**Pull request merged**
